{
 "title": "Ping Exporter",
 "tags": [ "network" ],
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Selected host",
    "query": {
     "query": "label_values(status_hosts_list,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Subnet hosts status",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_hosts_count", "legendFormat": "Active hosts count" },
    { "expr": "inactive_hosts_count", "legendFormat": "Inactive hosts count" }
   ]
  },
  {
   "title": "Hosts changing status",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "changes(status_hosts_list{host=~\"$host\"}[$__interval]) > 0 or changes(status_hosts_list{host=~\"$host\"}[$__interval]) < 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "All active hosts",
   "type": "status-history",
   "gridPos": { "h": 30, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "status_hosts_list{host=~\"$host\"} == 1",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Active hosts Count",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 11, "x": 0, "y": 11 },
   "targets": [
    { "expr": "active_hosts_count", "legendFormat": "Active hosts count" }
   ]
  }
 ]
}